AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template to create an IAM Role for the Lambda function.

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: FraudDetectionLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              # S3 Access
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - "arn:aws:s3:::your-s3-bucket-name/*"
                  - "arn:aws:s3:::your-s3-bucket-name"

              # RDS Access
              - Effect: Allow
                Action:
                  - rds:DescribeDBInstances
                  - rds:Connect
                Resource: "*"

              # Rekognition Access
              - Effect: Allow
                Action:
                  - rekognition:DetectFaces
                  - rekognition:StartFaceDetection
                  - rekognition:GetFaceDetection
                Resource: "*"

              # SageMaker Access
              - Effect: Allow
                Action:
                  - sagemaker:InvokeEndpoint
                Resource:
                  - "arn:aws:sagemaker:your-region:your-account-id:endpoint/*"

              # SNS Access for Alerts
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: "arn:aws:sns:your-region:your-account-id:fraud-alerts-topic"

              # CloudWatch Logging
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"

Outputs:
  LambdaRoleArn:
    Description: ARN of the Lambda execution role
    Value: !GetAtt LambdaExecutionRole.Arn
    Export:
      Name: LambdaExecutionRoleArn
